import type { NavLink, OfferItem, ValueItem, WhyChooseItem, PropertyCardData } from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  { label: "Properties", href: "/properties" },
  { label: "Contact us", href: "/contact" },
];

export const OFFER_ITEMS: OfferItem[] = [
  {
    number: "01",
    title: "Purpose Built Specialist Disability Accommodation",
    description:
      "NALA specializes in properties that meet individual needs. NALA villas can be customized during construction to fit specific requirements.",
    imageSrc: "/images/offer-01.jpg",
  },
  {
    number: "02",
    title: "Reliability and Care through our SIL Partners",
    description:
      "By partnering with industry leading and experienced SIL providers, NALA ensures its residents consistently receive the best possible care.",
    imageSrc: "/images/offer-02.jpg",
  },
  {
    number: "03",
    title: "Medium Term Accommodation provides flexible housing.",
    description:
      "NALA provides NDIS participants with the valuable option for MTA lasting up to 90 days, allowing them to carefully select their preferred SDA.",
    imageSrc: "/images/offer-03.jpg",
  },
  {
    number: "04",
    title: "Individually Tailored Luxury Villas for You",
    description:
      "NALA specializes in properties that meet individual needs. NALA villas can be customized during construction to fit specific requirements.",
    imageSrc: "/images/offer-04.jpg",
  },
];

export const VALUE_ITEMS: ValueItem[] = [
  { number: "01", title: "Follow your ethics", imageSrc: "/images/value-1.jpg" },
  { number: "02", title: "Residents needs come first", imageSrc: "/images/value-2.jpg" },
  { number: "03", title: "Take pride in your work", imageSrc: "/images/value-3.jpg" },
];

export const WHY_CHOOSE_ITEMS: WhyChooseItem[] = [
  {
    title: "Tailored Homes",
    description: "Spacious homes that strive for excellence and innovation",
    imageSrc: "/images/why-choose-1.png",
  },
  {
    title: "Convenient Locations",
    description: "Homes in accessible locations for family, friends, and caregivers.",
    imageSrc: "/images/why-choose-2.jpg",
  },
  {
    title: "20 years in Property",
    description: "Ensures functional, easily adaptable, comfortable and safe living",
    imageSrc: "/images/why-choose-3.jpg",
  },
];

export const PROPERTY_SLIDES = [
  {
    id: "slide-1",
    cards: [
      {
        id: "1",
        title: "Ocean View Drive, Manly",
        imageSrc: "/images/property-1.jpg",
        silProvider: "CareConnect",
        supportLevel: "Medium Physical Support",
      },
      {
        id: "2",
        title: "Ocean View Drive, Manly",
        imageSrc: "/images/property-2.jpg",
        villas: [
          { name: "Home", bedrooms: 3, bathrooms: 2 },
          { name: "Villa 1", bedrooms: 3, bathrooms: 2 },
          { name: "Villa 2", bedrooms: 2, bathrooms: 1 },
        ],
      },
      {
        id: "3",
        title: "Ocean View Drive, Manly",
        imageSrc: "/images/property-3.jpg",
        silProvider: "CareConnect",
        supportLevel: "Medium Physical Support",
      },
    ],
  },
];

export const PROPERTY_LISTINGS: PropertyCardData[] = [
  {
    id: "1",
    title: "Reservoir Road, Blacktown",
    imageSrc: "/images/property-1.jpg",
    silProvider: "Thrive365",
    supportLevel: "High Physical Support",
    villas: [
      { name: "Home", bedrooms: 6, bathrooms: 2 },
      { name: "Villa", bedrooms: 6, bathrooms: 2 },
    ],
  },
  {
    id: "2",
    title: "Ocean View Drive, Manly",
    imageSrc: "/images/property-2.jpg",
    silProvider: "CareConnect",
    supportLevel: "Medium Physical Support",
    villas: [
      { name: "Home", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 1", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 2", bedrooms: 2, bathrooms: 1 },
    ],
  },
  {
    id: "3",
    title: "Parkview Lane, Penrith",
    imageSrc: "/images/property-3.jpg",
    silProvider: "CareConnect",
    supportLevel: "Medium Physical Support",
    villas: [
      { name: "Home", bedrooms: 4, bathrooms: 2 },
      { name: "Villa 1", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 2", bedrooms: 3, bathrooms: 1 },
    ],
  },
  {
    id: "4",
    title: "Hilltop Crescent, Liverpool",
    imageSrc: "/images/property-1.jpg",
    silProvider: "AbilityCare",
    supportLevel: "Fully Accessible",
    villas: [
      { name: "Home", bedrooms: 5, bathrooms: 3 },
      { name: "Villa", bedrooms: 4, bathrooms: 2 },
    ],
  },
  {
    id: "5",
    title: "Sunrise Boulevard, Parramatta",
    imageSrc: "/images/property-2.jpg",
    silProvider: "Thrive365",
    supportLevel: "High Physical Support",
    villas: [
      { name: "Home", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 1", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 2", bedrooms: 2, bathrooms: 1 },
    ],
  },
  {
    id: "6",
    title: "Meadow Ridge, Castle Hill",
    imageSrc: "/images/property-3.jpg",
    silProvider: "CareConnect",
    supportLevel: "Medium Physical Support",
    villas: [
      { name: "Home", bedrooms: 4, bathrooms: 2 },
      { name: "Villa 1", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 2", bedrooms: 3, bathrooms: 2 },
    ],
  },
  {
    id: "7",
    title: "Lakeside Avenue, Campbelltown",
    imageSrc: "/images/property-1.jpg",
    silProvider: "AbilityCare",
    supportLevel: "Fully Accessible",
    villas: [
      { name: "Home", bedrooms: 5, bathrooms: 2 },
      { name: "Villa", bedrooms: 4, bathrooms: 2 },
    ],
  },
  {
    id: "8",
    title: "Harbour Street, Wollongong",
    imageSrc: "/images/property-2.jpg",
    silProvider: "Thrive365",
    supportLevel: "Medium Physical Support",
    villas: [
      { name: "Home", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 1", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 2", bedrooms: 2, bathrooms: 1 },
    ],
  },
  {
    id: "9",
    title: "Valley View Road, Richmond",
    imageSrc: "/images/property-3.jpg",
    silProvider: "CareConnect",
    supportLevel: "High Physical Support",
    villas: [
      { name: "Home", bedrooms: 4, bathrooms: 2 },
      { name: "Villa 1", bedrooms: 3, bathrooms: 2 },
      { name: "Villa 2", bedrooms: 3, bathrooms: 1 },
    ],
  },
];

export const COMPANY_INFO = {
  name: "NALA Properties",
  tagline: "SDA Properties by Nanak Accessible Living Australia",
  email: "info@nalaproperties.com.au",
  ndisProvider: "4-GMPNJSS",
  copyright: "Copyright © 2020. Nanak Accessible Living Australia All rights reserved.",
};

export const FOOTER_LINKS = NAV_LINKS;

export const FOOTER_CLOUDS = [
  { top: 71, left: 0, scale: 0.78, duration: 1000, direction: 0, opacity: 1, img: "/images/cloud.png" },
  { top: 84.5, left: 86.6, scale: 1.12, duration: 3739, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 9.8, left: 27.1, scale: 1.2, duration: 3294, direction: -1, opacity: 1, img: "/images/cloud3.png" },
  { top: 96.7, left: 2.5, scale: 0.71, duration: 6088, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 55.6, left: 48.7, scale: 1.32, duration: 3866, direction: -1, opacity: 1, img: "/images/cloud5.png" },
  { top: 58.5, left: 75.9, scale: 0.65, duration: 5645, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 62.4, left: 26.7, scale: 0.71, duration: 6307, direction: -1, opacity: 1, img: "/images/cloud.png" },
  { top: 21.1, left: 61.9, scale: 1.22, duration: 6815, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 77.3, left: 78.5, scale: 0.83, duration: 3077, direction: -1, opacity: 1, img: "/images/cloud3.png" },
  { top: 88.3, left: 73.1, scale: 1.01, duration: 4894, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 100.2, left: 10, scale: 0.83, duration: 1000, direction: 0, opacity: 1, img: "/images/cloud5.png" },
  { top: 49, left: 64.8, scale: 1.25, duration: 4520, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 82.2, left: 19.3, scale: 1.1, duration: 4042, direction: -1, opacity: 1, img: "/images/cloud.png" },
  { top: 48.8, left: 80, scale: 1.25, duration: 3607, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 54.7, left: 23.4, scale: 0.85, duration: 5150, direction: -1, opacity: 1, img: "/images/cloud3.png" },
  { top: 7.6, left: 20.2, scale: 1.31, duration: 6493, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 12, left: 28.8, scale: 1.18, duration: 6613, direction: -1, opacity: 1, img: "/images/cloud5.png" },
  { top: 41.6, left: 82.2, scale: 1.48, duration: 5776, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 87.5, left: 33.9, scale: 0.76, duration: 4921, direction: -1, opacity: 1, img: "/images/cloud.png" },
  { top: 87.7, left: 7.7, scale: 0.76, duration: 6727, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 100.8, left: 90, scale: 1.4, duration: 1000, direction: 0, opacity: 1, img: "/images/cloud3.png" },
  { top: 57.5, left: 81.7, scale: 0.77, duration: 4704, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 48.6, left: 4.4, scale: 0.76, duration: 6216, direction: -1, opacity: 1, img: "/images/cloud5.png" },
  { top: 61.4, left: 2.1, scale: 1.03, duration: 6836, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 15.2, left: 13.2, scale: 1.47, duration: 3521, direction: -1, opacity: 1, img: "/images/cloud.png" },
  { top: 90.8, left: 30.1, scale: 0.94, duration: 4064, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 96.6, left: 83.6, scale: 1.19, duration: 3993, direction: -1, opacity: 1, img: "/images/cloud3.png" },
  { top: 66.8, left: 85.5, scale: 1.03, duration: 6205, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 71.4, left: 5, scale: 1.09, duration: 6136, direction: -1, opacity: 1, img: "/images/cloud5.png" },
  { top: 69.2, left: 44, scale: 1.2, duration: 5054, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 100.9, left: 60.5, scale: 0.61, duration: 0, direction: 0, opacity: 1, img: "/images/cloud.png" },
  { top: 15.4, left: 51.5, scale: 0.82, duration: 3789, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 92.2, left: 49.6, scale: 1.41, duration: 4311, direction: -1, opacity: 1, img: "/images/cloud3.png" },
  { top: 91.6, left: 49.8, scale: 0.84, duration: 3005, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 90.9, left: 59.1, scale: 1.41, duration: 4521, direction: -1, opacity: 1, img: "/images/cloud5.png" },
  { top: 52.2, left: 89.8, scale: 1.28, duration: 3887, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 48.6, left: 18.9, scale: 1.32, duration: 6375, direction: -1, opacity: 1, img: "/images/cloud.png" },
  { top: 76.1, left: 29, scale: 1.29, duration: 3718, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 8.5, left: 61.6, scale: 0.99, duration: 3547, direction: -1, opacity: 1, img: "/images/cloud3.png" },
  { top: 30.1, left: 5.8, scale: 0.79, duration: 3047, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 90.7, left: 10.4, scale: 0.69, duration: 0, direction: 0, opacity: 1, img: "/images/cloud5.png" },
  { top: 58.1, left: 95, scale: 1.21, duration: 5666, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 52.1, left: 52.9, scale: 0.86, duration: 6978, direction: -1, opacity: 1, img: "/images/cloud.png" },
  { top: 58.5, left: 18.4, scale: 1.28, duration: 6410, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 38.8, left: 50.8, scale: 1.08, duration: 6160, direction: -1, opacity: 1, img: "/images/cloud3.png" },
  { top: 56.2, left: 58.6, scale: 0.81, duration: 5495, direction: -1, opacity: 1, img: "/images/cloud4.png" },
  { top: 15.8, left: 23.3, scale: 0.95, duration: 3668, direction: -1, opacity: 1, img: "/images/cloud5.png" },
  { top: 67.9, left: 42.1, scale: 0.81, duration: 6627, direction: -1, opacity: 1, img: "/images/cloud6.png" },
  { top: 61.7, left: 88.1, scale: 1.42, duration: 5548, direction: -1, opacity: 1, img: "/images/cloud.png" },
  { top: 60, left: 7.2, scale: 1.07, duration: 4472, direction: -1, opacity: 1, img: "/images/cloud2.png" },
  { top: 100, left: 90.2, scale: 0.81, duration: 0, direction: 0, opacity: 1, img: "/images/cloud3.png" },
  { top: 92, left: 42.8, scale: 0.92, duration: 6727, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 18.8, left: 8.3, scale: 1.08, duration: 3699, direction: 1, opacity: 1, img: "/images/cloud5.png" },
  { top: 54, left: 68.2, scale: 1.18, duration: 5125, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 10.8, left: 56.9, scale: 0.6, duration: 6544, direction: 1, opacity: 1, img: "/images/cloud.png" },
  { top: 14.3, left: 4.3, scale: 0.79, duration: 6312, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 48.6, left: 50.2, scale: 1.07, duration: 5559, direction: 1, opacity: 1, img: "/images/cloud3.png" },
  { top: 85.2, left: 59.1, scale: 1.46, duration: 6159, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 14.2, left: 26, scale: 1.49, duration: 6600, direction: 1, opacity: 1, img: "/images/cloud5.png" },
  { top: 61.3, left: 69.1, scale: 0.94, duration: 3931, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 90, left: 52.8, scale: 0.89, duration: 0, direction: 0, opacity: 1, img: "/images/cloud.png" },
  { top: 38.3, left: 64.6, scale: 0.63, duration: 3055, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 71.8, left: 8.5, scale: 1.41, duration: 3284, direction: 1, opacity: 1, img: "/images/cloud3.png" },
  { top: 87.3, left: 39.8, scale: 0.95, duration: 4000, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 8.3, left: 12.3, scale: 0.61, duration: 4391, direction: 1, opacity: 1, img: "/images/cloud5.png" },
  { top: 88.7, left: 34.8, scale: 1.36, duration: 4558, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 8.9, left: 95.7, scale: 1.31, duration: 5886, direction: 1, opacity: 1, img: "/images/cloud.png" },
  { top: 47.4, left: 92.8, scale: 0.7, duration: 4022, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 3.2, left: 39.7, scale: 0.61, duration: 3386, direction: 1, opacity: 1, img: "/images/cloud3.png" },
  { top: 46, left: 62.6, scale: 1.17, duration: 5222, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 90.2, left: 49.9, scale: 0.69, duration: 0, direction: 0, opacity: 1, img: "/images/cloud5.png" },
  { top: 12.7, left: 15.1, scale: 0.69, duration: 3888, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 86.6, left: 90.7, scale: 1.02, duration: 3359, direction: 1, opacity: 1, img: "/images/cloud.png" },
  { top: 90.1, left: 47.5, scale: 0.65, duration: 6541, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 32.2, left: 5.8, scale: 1.21, duration: 6719, direction: 1, opacity: 1, img: "/images/cloud3.png" },
  { top: 60.9, left: 81.5, scale: 0.93, duration: 5623, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 22, left: 32.9, scale: 0.81, duration: 5257, direction: 1, opacity: 1, img: "/images/cloud5.png" },
  { top: 10.1, left: 48.2, scale: 1.4, duration: 4716, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 82.7, left: 15.1, scale: 0.62, duration: 6863, direction: 1, opacity: 1, img: "/images/cloud.png" },
  { top: 52.4, left: 33.6, scale: 1.12, duration: 5717, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 90.7, left: 56.8, scale: 1.27, duration: 0, direction: 0, opacity: 1, img: "/images/cloud3.png" },
  { top: 48.5, left: 77.3, scale: 0.62, duration: 3562, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 25.3, left: 8.1, scale: 0.81, duration: 6409, direction: 1, opacity: 1, img: "/images/cloud5.png" },
  { top: 25.5, left: 60.4, scale: 0.73, duration: 5486, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 81.3, left: 35.6, scale: 0.73, duration: 5195, direction: 1, opacity: 1, img: "/images/cloud.png" },
  { top: 54.7, left: 5.8, scale: 1.45, duration: 4643, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 67.5, left: 80.8, scale: 1.03, duration: 4587, direction: 1, opacity: 1, img: "/images/cloud3.png" },
  { top: 64.6, left: 42.6, scale: 0.85, duration: 4207, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 70, left: 0.7, scale: 1.24, duration: 3609, direction: 1, opacity: 1, img: "/images/cloud5.png" },
  { top: 42.5, left: 85, scale: 1.25, duration: 3910, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 90.7, left: 20.1, scale: 0.66, duration: 0, direction: 0, opacity: 1, img: "/images/cloud.png" },
  { top: 47.3, left: 70.1, scale: 0.91, duration: 5038, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 21.8, left: 88.6, scale: 1.23, duration: 5991, direction: 1, opacity: 1, img: "/images/cloud3.png" },
  { top: 66.6, left: 81.9, scale: 1.07, duration: 3037, direction: 1, opacity: 1, img: "/images/cloud4.png" },
  { top: 67.9, left: 19.8, scale: 1.02, duration: 6045, direction: 1, opacity: 1, img: "/images/cloud5.png" },
  { top: 86.2, left: 13, scale: 0.87, duration: 6591, direction: 1, opacity: 1, img: "/images/cloud6.png" },
  { top: 80.7, left: 62.9, scale: 1.35, duration: 3119, direction: 1, opacity: 1, img: "/images/cloud.png" },
  { top: 85.8, left: 86.3, scale: 0.77, duration: 6567, direction: 1, opacity: 1, img: "/images/cloud2.png" },
  { top: 51.7, left: 4.4, scale: 0.81, duration: 6929, direction: 1, opacity: 1, img: "/images/cloud3.png" },
  { top: 56.7, left: 19.4, scale: 0.99, duration: 6813, direction: 1, opacity: 1, img: "/images/cloud4.png" },
] as const;
